### ISSUE TITLE
ReviewFrom value doesn't take into account email: displayname usage in configuration

### ISSUE THREAD

**Issue by JamesDPC** [silverstripe/silverstripe-contentreview#202]
Hi folks

If you have this configuration per the documentation:

```yaml
SilverStripe\Control\Email\Email:
  admin_email:
    support@example.com: 'Support team'
```

The field in site settings will end up containing a JSONifed representation:

```json
{ "support@example.com": "Support team" }
```

... and the content review notification job will fail due to email address validation.
Easy to workaround by updating the field value in site settings. Picking out the email address from the config setting would be a better option, by detecting an array value.
